# Generated by Django 4.0.2 on 2022-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('facial_expressions', models.CharField(max_length=50)),
                ('audio_analysis', models.CharField(max_length=50)),
                ('accuracy', models.CharField(max_length=50)),
            ],
        ),
    ]
