# Generated by Django 4.0.2 on 2022-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_audio_analysis_keys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='profile',
            name='average_audio_emotions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_face_emotions',
            field=models.CharField(default='', max_length=50),
        ),
    ]
